name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore
      run: restore
    - name: Build
      run: build
    - name: Test
      run: test
